### ISSUE TITLE
Please release soon - "in" operator not working in 0.5.0

### ISSUE THREAD

**Issue by jfinkhaeuser** [tr11/python-configuration#12]
Hi,

I like your project's goals, and decided to integrate it into one of my projects. However, running my own tests, I found that in the released 0.5.0 version, the 'in' operator does not work:

```python
cfg = config.config_from_dict({'foo': 42})
assert 'foo' in cfg
```

Turns out you've added support for it in master thanks to the addition of `__iter__` and `__len__`. It would be nice if that saw the light of day.

**Comment by tr11** [comment]
I meant to release it last weekend but ended up running out of time. A reminder is always useful :+1:

**Comment by jfinkhaeuser** [comment]
Works like a charm, thanks!
