### ISSUE TITLE
How do you manage to get the arguments from pip install package[arg]

### ISSUE THREAD

**Issue by kenseii** [tr11/python-configuration#15]
Hello,
Sorry to post the question here, i know it is not really a project issue.
i am wondering how can someone can get the command argument like `[yaml, ...]`
from pip install, without passing `pip install python-configuration --install-option="--yaml=True"`.

i checked the setup but it doesnt mention how `pip install python-configuration[toml, yaml]` feature is implemented in setup.

Thank you

**Comment by tr11** [comment]
I'm not sure if this is what you want, but here's the `setup.py` file the packaging tool I'm using (`poetry`) generates:

```
# -*- coding: utf-8 -*-
from setuptools import setup

packages = ['config', 'config.contrib']

package_data = {'': ['*']}

extras_require = {
 'aws': ['boto3>=1.10.48,<2.0.0'],
 'azure': ['azure-keyvault>=4.0.0,<5.0.0', 'azure-identity>=1.1.0,<2.0.0'],
 'toml': ['toml>=0.10.0,<0.11.0'],
 'yaml': ['pyyaml>=5.1,<6.0']}

setup_kwargs = {
    'name': 'python-configuration',
    'version': '0.6.0',
    'description': '...',
    'author': 'Tiago Requeijo',
    'author_email': 'tiago.requeijo.dev@gmail.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': 'https://github.com/tr11/python-configuration',
    'packages': packages,
    'package_data': package_data,
    'extras_require': extras_require,
    'python_requires': '>=3.6,<4.0',
}


setup(**setup_kwargs)

```

**Comment by kenseii** [comment]
Thank you very much for the explaination,
Thats exactly what i needed. :-)
