### ISSUE TITLE
Add string interpolation

### ISSUE THREAD

**Issue by chinghwayu** [tr11/python-configuration#18]
First of all, thanks for quickly addressing the other items!

In this feature request, I propose to add string interpolation so that values can be dynamically generated based on other values. I will use a simple dict as example.

```
>>> a = {"var1":"{var2}", "var2":"test"}
>>> a
{'var1': '{var2}', 'var2': 'test'}
>>> a["var1"]
'{var2}'
>>> a["var1"].format(**a)
'test'
```
taking this a step further...
```
>>> a = {"var1":"{var2}", "var2":"{var3}", "var3":"test"}
>>> a
{'var1': '{var2}', 'var2': '{var3}', 'var3': 'test'}
>>> a["var1"].format(**a)
'{var3}'
>>> a["var1"].format(**a).format(**a)
'test'
```

The solution for dict would be to (not tested, for illustrative purposes):
``` python
class myconfig(mydict):
    @interpolate
    def __getitem__ # same as normal dict
...

def interpolate(func):
    def getitem(s, key):
        var = func(s, key)
            if var has regex pattern {var} # pseudo code from here on...
                var.format(**mydict)
            if var has regex pattern
                var = getitem(s, key) # recursively call to interpolate
```

Hopefully, I explained well enough and you find this to be a useful feature. I currently have a local implementation but would like to see this embedded into the library. Thanks!

**Comment by tr11** [comment]
To make sure, you want the interpolation to happen automatically, right?

**Comment by chinghwayu** [comment]
> To make sure, you want the interpolation to happen automatically, right?

Yes. For example:
```
>>> cfg["var1"]
'test'
```

**Comment by tr11** [comment]
Take a look at this branch: https://github.com/tr11/python-configuration/tree/interpolation. I think it does what you want.  If it looks good, I'll merge this into a new version.
