### ISSUE TITLE
Interpolation circular reference workaround

### ISSUE THREAD

**Issue by chinghwayu** [tr11/python-configuration#22]
There's a use case where at the lowest of the heirarchy I utilize interpolation however the variable needs to be to appended such as:
`var1 = "{var1}/something`

I have a potential workaround but I was wondering if anyone has possible workarounds I haven't considered? Thanks!

**Comment by tr11** [comment]
Can you give a concise example of what you mean? A config example and the expected outcomes, that is.

**Comment by chinghwayu** [comment]
Directory structure is such that there is a top-level conf.py and a subdirectory with a conf.py

    ├── dir
    │   └── conf.py
    └── conf.py
conf.py has content:
`var1 = "something"`

dir/conf.py has content:
`var1 = "{var1}/else"`

If loading the top level conf only:
`cfg = config("conf.py", interpolate=True)`
`cfg["var1"]` would result in `"something"`

If loading both:
```
module_list = ["conf.py", "dir/conf.py"]
cfg = config(*module_list, interpolate=True)
```
Currently, `cfg["var1"]` still results in `"something"` due to what I'm guessing is circular referencing. However, I'd like it to result in `"something/else"`.

We use levels of hierarchy to parameterize. In certain cases, we'd like to append to the value through configuration. Our current workaround is to obtain `cfg["var1"]` and then conditionally append to the value.

Hope that explains it better.

**Comment by tr11** [comment]
This is not going to work the way you want. In your example, the library will traverse the configs from left to right so as soon as it finds the `var1 = "something"` it stops since `var1` is resolved and requires no interpolation.

**Comment by chinghwayu** [comment]
> This is not going to work the way you want. In your example, the library will traverse the configs from left to right so as soon as it finds the `var1 = "something"` it stops since `var1` is resolved and requires no interpolation.

sorry, the example had the values in the list reversed. In this case:
`module_list = ["dir/conf.py", "conf.py"]`
will result in `Cycle detected while interpolating keys` which is what I'm referring to when I say "circular reference".

I understand in both cases that it's not going to work the way I want. I was wondering if you could think of a different more elegant workaround. 😃

**Comment by chinghwayu** [comment]
When interpolating, is there a way to avoid trying to interpolate itself and only from "parent" configurations?
If not possible as part of the primary value extraction algorithm with multiple sets, perhaps enable only as part of .as_dict() when flattening?

**Comment by tr11** [comment]
I think I may have a fix, but need to test it.  Basically, when performing interpolations it keeps track of the depth for each variable. In that way, we never try to interpolate itself and instead go one level deeper in the hierarchy.

**Comment by tr11** [comment]
This issue is a bit tricky since we need to decide the order of interpolation. For example, what should be the value of `var2` if

conf.py has content:
`var1 = "something"`
`var2 = "{var1}"

dir/conf.py has content:
`var1 = "{var1}/else"`
`var2 = "{var2}/else"

Should the first `var2` pick it up from conf.py or dir/conf.py?

**Comment by SGStino** [comment]
this looks like full-on inheritance with virtual methods, 
`var2` would resolve to `'{var2}/else'.format(var2='{var1}'.format(var1='{var1}/else'.format(var1='something')))` so, `something/else/else` if it would implement the inheritance like an OOP language would with method overrides.

However, from a config point of view, this might look confusing to some/most? Perhaps the required use of an explicit `super` vs implicit `self` keyword or something to make it more explicit could help?

**Comment by tr11** [comment]
Yeah, it does look like that. The complication here is that we need to support the recursive calls to the same variable.

**Comment by chinghwayu** [comment]
> Should the first `var2` pick it up from conf.py or dir/conf.py?

For our internal interpolation implementation, it's a bit different that the one in this library. We look at it from a hierarchical perspective meaning the lower level configurations _override_ the previous. It is a "one way" process and doesn't have sets where the interpolation value can be from any other set. The first configuration establishes a template where lower level configurations provide interpolation values or alters how a value is generated.

So to answer the question, if `conf.py` is loaded first, then `dir/conf.py` is loaded, `var2` would be "something/else". The order is:
load conf.py - `var1` and `var2` have been established
load dir/conf.py - {var2} will look to see if var2 has been established. Since it has, it will take that value, insert it, and then reestablish `var2`

I understand the underlying implementation in this library is a bit different which is why I suggest to only enabled this feature when flattening using .as_dict() if it wasn't possible or too complex to implement.

**Comment by tr11** [comment]
I'd like to add something like this.  Let's keep discussing so we come up with something robust enough that allows for the behavior you mentioned.

**Comment by chinghwayu** [comment]
What if there was an `ordered` option which would have the algorithm interpolate in such "overriding" behavior?
The default is `None` which would use the original algorithm. Two options `ordered=ascending` or `ordered=descending` would switch the algorithm to this "overriding" behavior and determine the "direction".

**Comment by tr11** [comment]
Take a look at https://github.com/tr11/python-configuration/pull/34. I think it does some of what you want.

**Comment by chinghwayu** [comment]
Unforutnately, I'm not able to get the use case I've described to work.
https://github.com/tr11/python-configuration/issues/22#issuecomment-648438444

**Comment by tr11** [comment]
Did you check the interpolation tests?  I used the case you mentioned.

**Comment by chinghwayu** [comment]
> Did you check the interpolation tests? I used the case you mentioned.

oh, I didn't noticed the enums. Is the difference between DEEP and DEEP_NO_BACKTRACK such that Backtrack the "one way" method?

**Comment by tr11** [comment]
The no backtrack is such that a variable will never be interpolated "up" in the list of configs. That is, if we want to interpolate from the lowest priority config, we will only use that one to resolve the interpolation variables.

Take a look at the test `test_interpolation_same_variable_4`, it shows the differences between the two methods.

**Comment by tr11** [comment]
Let me know if this works for you and I can merge it.

**Comment by chinghwayu** [comment]
> Let me know if this works for you and I can merge it.

It's working. I'm trying to dig up other real-world examples but you can go ahead and merge.
