### ISSUE TITLE
Improve "Gettting started" and "Developing" sections in docs

### ISSUE THREAD

**Issue by dwich** [tr11/python-configuration#50]
Good project but I got stuck with two things at the begining and I suppose I am not alone. I couldn't find basic example until I dug deep. It's also not easy to guess - where does the `config_from_*` come from and what is the name of the installed package.

What I missed in the "Getting started" section was:

```
from config import config_from_dict

cfg = {
    'a': {
        'b': 'value'
    }
}

cfg = config_from_dict(cfg)
```

I also wanted to download the code, run the tests and eventually contribute at least some docs improvements as a PR. I use different tools than poetry and was stuck again. What I missed was an example: After you clone git repo, install packages using
`poetry install` or `poetry install -E aws -E azure -E gcp -E toml -E yaml`.
To run all the tests run `pytest` or `poetry run pytest`.

If the test diplays a message `ValueError: Invalid tenant id provided.`, do this and that...

**Comment by maurete** [comment]
Not sure where I'm getting it wrong... Following the instructions in the documentation I tried the following:
```
$ pip install python-configuration
Collecting python-configuration
  Downloading python_configuration-0.8.1-py3-none-any.whl (22 kB)
Installing collected packages: python-configuration
Successfully installed python-configuration-0.8.1
```
Then:
```$ python3
Python 3.9.1 (default, Dec  8 2020, 07:51:42) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import config
>>> config(('env','PREFIX'),('dict',{}))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
>>> config.config(('env','PREFIX'),('dict',{}))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'config' has no attribute 'config'
>>> 
```

**Comment by tr11** [comment]
Thank you for the suggestions.  Could you submit a PR with those changes? Thanks!

**Comment by jDavidnet** [comment]
I'm new to python, but I'm an experienced full stack developer in other languages.

in my project I'm trying to load a default config file, and a 'local override' file, but I'm having trouble with the above content, and referencing the proper path of my config files.

**Comment by jDavidnet** [comment]
I had to write a small function to fix the relative path to project files.

```python
def fix_path(file_path):
    """fixes a path so project files can be located via a relative path"""
    script_path = os.path.dirname(__file__)
    return os.path.normpath(os.path.join(script_path, file_path))
```

**Comment by tr11** [comment]
What Python version are you using?
