### ISSUE TITLE
[Investigation] Limitations of python-configuration that prevent others from adopting it.

### ISSUE THREAD

**Issue by movermeyer** [tr11/python-configuration#53]
I've recently been writing a configuration-loading system for a new library. I was copying the system used by [coverage-py](https://coverage.readthedocs.io/en/coverage-5.4/config.html). 
Now that I've stumbled upon `python-configuration` and I wonder if it might be a better solution.

I'm writing this issue to document what I've discovered, which might give ideas for the future direction of `python-configuration`.

-----

[coverage-py](https://coverage.readthedocs.io/en/coverage-5.4/config.html) loads its configuration from a [hierarchy of locations](https://github.com/nedbat/coveragepy/blob/a559e7cc2cd4de6095aa84347e36a7c526cd6147/coverage/config.py#L515-L520), including locations in some shared config files (eg. `setup.cfg`, `tox.ini`, `pyproject.toml`).

A few things make their config loading needs different from what `ConfigurationSet` currently offers:

* The keys in INI/toml files must have a specific prefix/namespace (`coverage:`), in order to avoid colliding with the keys of other libraries in the shared config file
* Once a file is found that contains relevant keys, no other files are considered.
* Missing files are ignored
* Configuration options are [defined in a schema](https://github.com/nedbat/coveragepy/blob/a559e7cc2cd4de6095aa84347e36a7c526cd6147/coverage/config.py#L341-L402):
    * Values can have types
    * Unknown keys are raised as exceptions
    * They also have custom type definitions and handlers to parse/convert/deserialize them.

See their [documentation](https://coverage.readthedocs.io/en/coverage-5.4/config.html) or [the source](https://github.com/nedbat/coveragepy/blob/a559e7cc2cd4de6095aa84347e36a7c526cd6147/coverage/config.py) for details.

**Comment by chinghwayu** [comment]
@tr11 , what are you plan on maintaining this library going forward?

@movermeyer , are you interesting in forking and co-maintaining with myself if we don't hear back?

**Comment by movermeyer** [comment]
@chinghwayu Have you managed to hear back from @tr11 ? Let's not fork unless absolutely necessary.

Unfortunately, I don't have much time to help (I'm already committed to too many other projects right now).
I could do some initial help to get things set up initially, but someone else would have to be the primary maintainer / coder.

**Comment by chinghwayu** [comment]
@movermeyer haven't heard back

**Comment by tr11** [comment]
Hey guys, my apologies for the delay getting back to you.  Things were a bit crazy at work, but I'm back at actively using and maintaining it.

**Comment by chinghwayu** [comment]
Great to have you back. Can you push out a release with the recent merges?

**Comment by tr11** [comment]
Will do! Just need to figure out what's missing on the tests side now to get full coverage
