### ISSUE TITLE
Any interest in non-file backends?

### ISSUE THREAD

**Issue by stucchio** [tr11/python-configuration#6]
Greetings,

Great library. Perfectly meets my needs - I built several internal versions of this, glad to have a standard open source lib. 

In some of my environments I have the need of a cloud-based configuration backend, to avoid storing secrets in plain text on a server. For Azure I wrote this backend:

https://gist.github.com/stucchio/8a0c6c57cea7452eed8e7001877ae2fd

Near as I can tell it's a drop-in replacement for existing `Configuration` objects, but it uses Azure Key Vault instead.

Any interest in adding such functionality? Happy to clean it up if you are.

**Comment by tr11** [comment]
That's a great idea, this would be a good addition to the library.
I'm not too familiar with the Azure Key Vault; what's the best way to test the library in this case?

**Comment by stucchio** [comment]
I can think of two ways to test it:

1. Create an Azure account and populate it with test data. (At least for the short run I can create one and give you access for testing - all you'd need to do is install the deps to use it.)
2. Build a mock of the `self.kvclient` variable. This will work, provided the mock correctly represents the semantics of Azure Key Vault. (Of course, that's the hard part - apart from getting that right, the code here is pretty simple.)

I can't figure out from the existing lib what would be the most consistent way, there doesn't seem to be much precedent. What do you think is best?

**Comment by tr11** [comment]
I'd prefer the second one to make sure we can run locally without any issues, but we can definitely add a pytest marker that would run with online access to Azure.  
Looking at https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/keyvault/azure-keyvault-secrets/tests, maybe we can do something similar to those tests to mock the client.

**Comment by tr11** [comment]
@stucchio, do you happen to have test data we could use (temporarily) to check whether the implementation is correct?  I made a few changes to allow for generic key services and would like to check it is working fine.  Thanks!

**Comment by stucchio** [comment]
I'll create one today. Do you have a branch I can take a look at to test myself also? I can also try writing that mock.

**Comment by tr11** [comment]
Here it is: https://github.com/tr11/python-configuration/tree/issue-6-azure.  Differences to your gist are mainly cleanup and adding some typing.

**Comment by stucchio** [comment]
Try these credentials:

clientId                       : 7518b2c4-df3a-4402-8add-dcd1243027fd
clientSecret                   : 21e05218-cd9a-4a8c-b9f7-c7b5212fcb22
tenantId                       : e20cecd5-5ae7-460d-802f-1c5c3a6c3cca
vault-name                  : pythonconfigtest

I'll leave these active for the next day or so.

**Comment by stucchio** [comment]
Added a mock of the keyvault, which allows local testing.

https://github.com/tr11/python-configuration/pull/7

**Comment by tr11** [comment]
I made a few changes to your PR to make sure we have 100% coverage and all tests pass. Could you test the new code at https://github.com/tr11/python-configuration/tree/issue-6-azure?  If it looks good I'll merge your PR and merge the changes.

**Comment by stucchio** [comment]
Looks good to me. I have tested it and can also successfully load configuration from my Azure account.

**Comment by tr11** [comment]
Closed by #7.
