### ISSUE TITLE
Optional config from file

### ISSUE THREAD

**Issue by Teivaz** [tr11/python-configuration#61]
I need to create a user configuration file that if present would override the basic config.
```
base.config.json - checked in
config.json - gitignore
```

But the following code does not work. I need to separately check for the config file and then modify the configuration sources.
```py
cfg = ConfigurationSet(
    config_from_env(prefix="app_config"),
    config_from_json("config.json", read_from_file=True), # Throws error when file is not present
    config_from_json("base.config.json", read_from_file=True),
)
```

It would be nice to have this case handled by the library instead. The interface can look like this:
```py
config_from_json("config.json", read_from_file=True, file_optional=True)
```

**Comment by tr11** [comment]
Isn't this accomplished with https://github.com/tr11/python-configuration/blob/11177291263b6f8a36c241a65c3bd5834f0919c9/tests/test_configuration_set.py#L601?

**Comment by Teivaz** [comment]
This will only partially solve the problem. When I need to specify as optional only one file this approach would be too permissive. In my case I need to always have the base config and throw an error when it is absent. But the user config is optional.

```
cfg = ConfigurationSet(
    config_from_env(prefix="app_config"),
    config_from_json("config.json", read_from_file=True, file_optional=True),
    config_from_json("base.config.json", read_from_file=True),
)
```

**Comment by tr11** [comment]
I see, you need the `ignore_missing_paths` or `file_optional` in your example to be pushed down to each `config_from_<filetype>` handler, right?

**Comment by Teivaz** [comment]
Yes, I need to be able to control each config file's options individually.
The approach I'm using is following:
1. Base config is essential and is a part of the repo. It should always be present as it contains defaults.
2. Then the user config is optional it can be stored in the user directory or in the working directory of the application that is being configured. If present this config has precedence over the base config.
3. Then finally the environment variables configs have precedence over all other configs.

**Comment by tr11** [comment]
This should be doable without any breaking changes. I'll have a branch with this soon for you to test.

**Comment by tr11** [comment]
Can you test the PR https://github.com/tr11/python-configuration/pull/72 to see if it works for your use case? You should be able to now use a `ConfigurationSet` as follows:
```
cfg = ConfigurationSet(
    config_from_env(prefix="app_config"),
    config_from_json("config.json", read_from_file=True, ignore_missing_paths=True),
    config_from_json("base.config.json", read_from_file=True),
)
```
