### ISSUE TITLE
Can't load python-configuration in a Python IDLE shell 

### ISSUE THREAD

**Issue by PFaurel** [tr11/python-configuration#67]
If you run IDLE Python  shell then try to load config, it doesn't load the expected module because idlelib already contains a config module.
![image](https://user-images.githubusercontent.com/15892712/139917424-889bf90e-dfb6-4d62-a5ec-8a72d410b154.png)

=> \Lib\idlelib\config is loaded first and \Lib\site-packages\config cannot be loaded

**Comment by tr11** [comment]
I'm not sure what we can do here if a particular library or IDE already uses a config import.

**Comment by PFaurel** [comment]
Sorry, it isn't a particular library : idlelib is a part of the standard Python package from  https://www.python.org.
python-configuration is a particular library - and it's great ! - but this case could avoid its usage by some developers because of this issue.

A solution is to rename this module in a next release.
'config' is quit generic and could create confusion with a lot of libs, why didn't you keep the package name (python_configuration) ?
